### ISSUE TITLE
Getting the rendered image

### ISSUE THREAD

**Issue by sr71684** [JeromeEippers/ipywebgl#1]
Hello,

epic library. Two questions:

1. Is it possible to get the rendered image instead of just looking at the result on the canvas? Ideally I'd want a numpy array with the rendered result. 
2. Possible to create a bunch of moving spheres inside a render loop?

**Comment by JeromeEippers** [comment]
Hello,

Thanks. 

1. It is not possible today as I haven't implemented the readpixel command.  It is something I can add. How would you want to use that feature?  Because reading back from webgl is always slow. 
2. Yes it is possible, you can have a look at the end of the "instanced" example where I animate a bunch of line.

Cheers

**Comment by sr71684** [comment]
Thanks for the quick response!

I'm building an n-body astrodynamics sim for eclipsing exoplanets around a their host star (practically, this is just orbiting spheres). Ideally, I run one iteration of my dynamics loop, update the position of the spheres, and get the rendered frame (somehow). I need the rendered frame for post-processing downstream. I'd expect this `read_back_image()` to be called every frame, and in a given simulaiton, there'd be on the order of 10,000 frames. 

Or if reading back from webgl is slow we could, at the end of a simulation, get a sequence of rendered images, returning a (N,W,H,3) numpy array (num frames, width, height, rbg)

**Comment by JeromeEippers** [comment]
Hello,

I've update the project to version 0.4.0 that supports a get_image_data function.

See the documentation :
https://ipywebgl.readthedocs.io/en/latest/examples/get_image_data.html

Cheers

**Comment by sr71684** [comment]
Nice! Thanks for the quick turn around on this :+1:
