### ISSUE TITLE
Uniform Bool Passing

### ISSUE THREAD

**Issue by CyanYou** [JeromeEippers/ipywebgl#2]
Hello! Nice library! I have been searching in the API reference and I'm wondering if there is a way to pass a uniform bool into the shader?

**Comment by CyanYou** [comment]
Also is there a way to get the attribute and uniform inside shader just like getAttribuLocation and getUniformLocation?

**Comment by JeromeEippers** [comment]
Hello CyanYou,

I've made a quick example on how to pass a boolean to a shader here :
https://github.com/JeromeEippers/ipywebgl/blob/main/examples/uniform_bool.ipynb

Basically, you can define a uniform as boolean in the shader, but there is no support on webgl2 to directly send a boolean, so you have to send it as uint32 instead.
https://developer.mozilla.org/en-US/docs/Web/API/WebGL2RenderingContext/uniform

For the getAttributeLocation and GetUniformLocation, this has been abstracted away in this library so every function that would use an attribute location or a uniform location will expect the name instead.  
The GetUniformLocation has been done for you when you created the program. You can see it if you display the program in the notebook; see the end of the uniform_bool example.

For the getAttributeLocation, you can either let the system decide the attribute location and all will be mapped for you when you do a create_vertex_array_ext (see introduction_extended example)
Or you can force the attribute location manually so a same vao can be used with different programs; see the shadow example.

Regards,
Jerome

**Comment by CyanYou** [comment]
Hello Jerome

That’s so great! Thanks for you detailed explanation!

All the best,
You Peng



Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
